# Research assignment 4


[Carmen Salazar]

[Ipums] 

[3/11/2020]

In [1]:
cd "/Users/karminsalazar/Desktop/Masters Thesis"

*set more off

*capture log close

*log using research_assignment4log20200311.log


use year statefip countyfip city puma cpuma0010 ///
migrate1 migpuma1 movedin age sex race educ incwage empstat bpl /// 
using usa_00005.dta, clear

/Users/karminsalazar/Desktop/Masters Thesis

In [2]:

*keep if _n<10000
*save ipums10000.dta, replace

(48,152,118 observations deleted)

file ipums10000.dta saved

In [70]:
*codebook race
*codebook sex
codebook puma

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
puma                                                                                                                                                                                                                                  public use microdata area
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

                  type:  numeric (long)

                 range:  [908,41003]                  units:  1
         unique values:  24                       missing .:  0/27,319

                  mean:   6611.34
              std. dev:   9962.28

           percentiles:        10%       25%       50%       75%       90%
                              1107      3414      4008      4112      8606

In [2]:
keep if year==2017

gen in_white = race==1 & movedin<4 & moved!=0

gen black=race==2

(44,972,077 observations deleted)

In [3]:
bysort puma: egen meaneduc=mean(educ)

In [4]:
recode sex (1=0) (2=1), gen(female)

(3190040 differences between sex and female)

In [7]:
bysort puma: egen float percent_female = pc(female)

In [8]:
gen all=1

In [9]:
foreach var in all in_white black { 
bysort puma: egen sum`var'2 = total(`var')
gen p_`var'= sum`var'2 / sumall
}

drop if p_black <.5 
*here we are telling stata to drop all people where less than half the of the population is black

(3,162,721 observations deleted)

In [10]:
describe

*IV of whites who moved in as indicator of gentrification

Contains data from usa_00005.dta
  obs:        27,319
 vars:            28                          10 MAR 2020 22:39
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              storage   display    value
variable name   type    format     label      variable label
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
year            int     %8.0g      YEAR       census year
statefip        byte    %8.0g      STATEFIP   state (fips code)
countyfip       int     %8.0g                 county (fips code)
city            int     %8.0g      CITY       city
puma            long    %12.0g                public use microdata area
cpuma0010       int     %8.0g                 consistent puma, 2000-2010
sex             byte    %8.0g      SEX        sex
age             byte    %8.0g      AGE        age
race            byte    %8.0g      RACE       race [general version]
bpl             int     %8.0g      BPL        birthplace [general version]
educ            byte    %8.0g      EDUC       educational attainment [general version]
empstat         byte    %8.0g      EMPSTAT    employment status [general version]
incwage         long    %12.0g                wage and salary income
migrate1        byte    %8.0g      MIGRATE1   migration status, 1 year [general version]
migpuma1        long    %12.0g                puma of residence 1 year ago
movedin         byte    %8.0g                 when occupant moved into residence
in_white        float   %9.0g
black           float   %9.0g
meaneduc        float   %9.0g
female          byte    %9.0g                 RECODE of sex (sex)
percent_female  float   %9.0g
all             float   %9.0g
sumall2         float   %9.0g
p_all           float   %9.0g
sumin_white2    float   %9.0g
p_in_white      float   %9.0g
sumblack2       float   %9.0g
p_black         float   %9.0g
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Sorted by: puma
     Note: Dataset has changed since last saved.

In [11]:
save ipumsblack50, replace

*use ipumsblack50 dataset for future assignments

file ipumsblack50.dta saved

In [12]:
%head

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  1. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  57 | black/af |     ohio | grade 12 | employed |   59000 | same hou |        0 |       0 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  2. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  11 |    white | puerto r |  nursery |      n/a |  999999 | same hou |        0 |       0 |        0 |     0 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  3. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 | female |  43 |    white | saudi ar |  4 years | employed |   34300 | abroad o |        1 |       0 |        0 |     0 | 5.818496 |      1 | .1219512 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  4. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  70 | black/af |  alabama | grade 12 | not in l |       0 | same hou |        0 |       0 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  5. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  23 | black/af |     ohio | 1 year o | not in l |   15000 | same hou |        0 |       0 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  6. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  32 | black/af |     ohio | grade 12 | employed |   42000 | same hou |        0 |       2 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  7. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  43 | black/af |     ohio | grade 12 | not in l |       0 | same hou |        0 |       0 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  8. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  54 | black/af |     ohio | grade 12 | employed |   40000 | same hou |        0 |       0 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  9. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 | female |  23 |    white |     ohio | 1 year o | employed |   25000 | same hou |        0 |       1 |        1 |     0 | 5.818496 |      1 | .1219512 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 10. | year | statefip | county~p |     city | puma | cpu~0010 |    sex | age |     race |      bpl |     educ |  empstat | incwage | migrate1 | migpuma1 | movedin | in_white | black | meaneduc | female | percen~e | all | sumall2 | p_all | sumin_~2 |
     | 2017 |     ohio |       35 | clevelan |  908 |      791 |   male |  53 | black/af |     ohio | grade 11 | not in l |       0 | same hou |        0 |       4 |        0 |     1 | 5.818496 |      0 |        0 |   1 |    1449 |     1 |       38 |
     |---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
     |                                    p_in_w~e                                    |                                    sumbla~2                                    |                                     p_black                                     |
     |                                     .026225                                    |                                        1115                                    |                                    .7694962                                     |
     +---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## 1. Develop hypotheses about interactions between your independent variables [1 pt]

You can use the GSS data, Student aid data, or your own data

    A. Write at least two hypotheses involving at least 2 of the following types of interactions
        1) nominal * nominal
        2) nominal * interval-ratio
        3) interval-ratio * interval-ratio
        
Hypothesis 1: I predict that my dependent variable of p_in_white (percent of residents that are  white               people who moved into the Census tract) will increase as my independent variables of p_black (percent of                 each district that is black) and average education level decreases.

Hypothesis 2: I predict that my dependent variable of p_in_white (percent of residents that are  white people who moved into the Census tract) will decrease as my independent variables of p_black (percent of each district that is black) and percentage of female residents increases.
       
   
        
    B. State the predicted direction of association between your dependent variable and:
        1) each of the 2 independent variables by themselves
        2) the interaction of the 2 indendent variables
        3) you can predict that there is no association
        
I predict there is an association between my dependent variable (p_in_white) and a decrease in the percent of each district that is black along with percentage of female residents within a tract. I also predict an association between percent of residents in Census tracts that are  white people who moved into the Census tract and the average education level of individuals. 

    C. Write a couple sentences about the theoretical reasons (prior knowledge / research) for each of your predictions
    -based on prior knowledge of research-
    
My predictions are based on literature that focuses on urban neighborhoods that have undergone disinvestments and economic decline, that experience a reversal, reinvestment, and an influx of a relatively well-off middle-and upper-class population (that includes more years of educational attainment). Gentrification is race and gender ordered that include perceptions of disorder within a neihborhood. Both percent Hispanic and percent black, along with perceptions of disorder attenuate the process and pace of gentrification. Neighborhood preferences suggest a racial hierarchy that parallels contemporary racial ordering of inequality, where white neighborhoods are "most favored, black neighborhoods the least, and Asian and Latino neighborhoods in the middle" (Hwang and Sampson.2014,p.728. Furthermore, women are also both agents and victims of gentrification, determined by their socioeconomic status and demographic characteristics, where white women are more likely to fuel the demand for gentrified housing and women of color are more vulnerable to displacement as result of gentrification.

## 2. Test your hypotheses [3 pts]

    A. For each hypothesized interactive relationship: use regression with the appropriate interaction syntax to estimate a 1 model with uninteracted variables and 1 model with interacted variables. Use --esttab-- with %html magic to output a model with the 2 tables
    
    B. Use margins and marginsplot with the appropriate syntax to visually represent your regression adjusted estimates for given nominal categories or at given interval-ratio values

In [13]:
est clear 

 eststo: reg p_in_white p_black percent_female meaneduc 
 eststo: reg p_in_white p_black c.percent_female##c.meaneduc

      Source |       SS           df       MS      Number of obs   =    27,319
-------------+----------------------------------   F(3, 27315)     =   4722.14
       Model |  3.90361137         3  1.30120379   Prob > F        =    0.0000
    Residual |  7.52675437    27,315  .000275554   R-squared       =    0.3415
-------------+----------------------------------   Adj R-squared   =    0.3414
       Total |  11.4303657    27,318  .000418419   Root MSE        =     .0166

--------------------------------------------------------------------------------
    p_in_white |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
---------------+----------------------------------------------------------------
       p_black |  -.0960614   .0009099  -105.57   0.000    -.0978449   -.0942779
percent_female |   .0407738   .0011147    36.58   0.000      .038589    .0429586
      meaneduc |   .0111846   .0002135    52.40   0.000     .0107663     .011603
         _cons |   .0245497   .0013312    18.44   0.000     .0219405    .0271589
--------------------------------------------------------------------------------
(est1 stored)


      Source |       SS           df       MS      Number of obs   =    27,319
-------------+----------------------------------   F(4, 27314)     =   3542.67
       Model |  3.90447573         4  .976118932   Prob > F        =    0.0000
    Residual |  7.52589002    27,314  .000275532   R-squared       =    0.3416
-------------+----------------------------------   Adj R-squared   =    0.3415
       Total |  11.4303657    27,318  .000418419   Root MSE        =     .0166

---------------------------------------------------------------------------------------------
                 p_in_white |      Coef.   Std. Err.      t    P>|t|     [95% Conf. Interval]
----------------------------+----------------------------------------------------------------
                    p_black |   -.096131   .0009107  -105.55   0.000    -.0979161   -.0943459
             percent_female |   .0157667   .0141629     1.11   0.266    -.0119933    .0435267
                   meaneduc |   .0108081   .0003013    35.87   0.000     .0102176    .0113986
                            |
c.percent_female#c.meaneduc |   .0043395   .0024501     1.77   0.077    -.0004628    .0091419
                            |
                      _cons |   .0267824   .0018333    14.61   0.000     .0231891    .0303758
---------------------------------------------------------------------------------------------
(est2 stored)

In [34]:

*census tract level data, move in and already black in census tract
*% of m/f in census tract level
*mean education for census tract level 

*c.age (treat educ as continuous)
*c.pmale (% of female is
*i. - if variable is categorical
*c. - continuous variable)

*new variables should be continuous - 
sum percent_female

    Variable |        Obs        Mean    Std. Dev.       Min        Max
-------------+---------------------------------------------------------
percent_fe~e |     27,319    .0878509    .0905823          0   .3154574

In [33]:
%html
esttab, stats(r2 N, labels("R2" "N")) cells(b(star fmt(3)) se(fmt(3) par)) ///
  nobase noconstant starlevels(* .1 ** .05 *** .01) mlabels("Model 1" "Model 2") ///
  coeflabels (percent_female "Percent Female Residents " Avg Year of Education c.percent_female#c.meaneduc "Female resident * Avg education") html

This front-end or document format cannot display HTML

In [61]:
qui margins percent_female, at(meaneduc=(0(1)11)) atmeans
marginsplot, title(FIGURE 1: Effect of average education on percent of female residents by race) scheme(538w)

## 3. Interpret your results [1 pt]

Write a couple sentences answering each of the following questions:

    A. Do the results support or contradict each of your hypotheses?
    
The results presented above support my hypotheses
    
    
    B. Why do the regression coefficients support or contradict your hypotheses?
    
The regression coefficients support my hypotheses because the second model has smaller SE values which indicate the observations are closer to the fitted line.The smaller the SE, the smaller the range of values of the coefficient.


    
    C. Why do your regression adjusted estimates from margins for nominal categories or given interval-ratio values support or contradict your hypotheses?
    
My regression adjusted estimates from my values support my hypotheses because they take into consideration more independent variables in my analysis that result in an adjusted estimate, that takes into account the effect due to all the additional independent variables included in the analysis.